"""
Story 1 Unit Tests: Fault Alert Threshold Logic
=================================================
Tests the severity classification logic from SP_EVALUATE_FAULT_ALERTS.
Runs entirely locally — no Snowflake connection required.

Acceptance Criteria (from PM backlog):
  [x] CRITICAL when fault_count > 20 OR max_temp > 130
  [x] HIGH     when fault_count > 10 OR max_temp > 115
  [x] No alert when vehicle is below both thresholds
  [x] Alert payload contains all required fields
  [x] aws_critical_alerts.json vehicles all trigger HIGH or CRITICAL
"""
import json
import os
import pytest
from datetime import datetime, UTC


# ── Mirror the SQL severity classification in Python for unit testing ──────────
def classify_severity(fault_count: int, max_engine_temp: float) -> str | None:
    """
    Python equivalent of the CASE WHEN logic in SP_EVALUATE_FAULT_ALERTS.
    Returns 'CRITICAL', 'HIGH', or None (no alert).
    """
    if fault_count > 20 or max_engine_temp > 130:
        return "CRITICAL"
    if fault_count > 10 or max_engine_temp > 115:
        return "HIGH"
    return None


def build_alert_payload(vin: str, fault_count: int, max_temp: float) -> dict | None:
    """Builds the alert dict that would be written to FAULT_NOTIFICATIONS."""
    severity = classify_severity(fault_count, max_temp)
    if severity is None:
        return None
    return {
        "vin_reference":   vin,
        "fault_count":     fault_count,
        "max_engine_temp": max_temp,
        "severity_label":  severity,
        "triggered_at":    datetime.now(UTC).isoformat(),
        "alert_source":    "SNOWFLAKE_TASK",
        "acknowledged":    False,
    }


# ── Tests ──────────────────────────────────────────────────────────────────────

class TestSeverityClassification:
    """Validates the CASE WHEN threshold logic from SP_EVALUATE_FAULT_ALERTS."""

    def test_critical_when_fault_count_exceeds_20(self):
        assert classify_severity(fault_count=21, max_engine_temp=90.0) == "CRITICAL"

    def test_critical_when_temp_exceeds_130(self):
        assert classify_severity(fault_count=5, max_engine_temp=131.0) == "CRITICAL"

    def test_critical_when_both_thresholds_breached(self):
        assert classify_severity(fault_count=25, max_engine_temp=135.0) == "CRITICAL"

    def test_high_when_fault_count_between_10_and_20(self):
        assert classify_severity(fault_count=15, max_engine_temp=90.0) == "HIGH"

    def test_high_when_temp_between_115_and_130(self):
        assert classify_severity(fault_count=2, max_engine_temp=120.0) == "HIGH"

    def test_exactly_at_critical_fault_boundary(self):
        assert classify_severity(fault_count=20, max_engine_temp=90.0) == "HIGH"    # 20 > 10, so HIGH
        assert classify_severity(fault_count=21, max_engine_temp=90.0) == "CRITICAL" # 21 > 20, so CRITICAL

    def test_exactly_at_high_fault_boundary(self):
        assert classify_severity(fault_count=10, max_engine_temp=90.0) is None   # not > 10
        assert classify_severity(fault_count=11, max_engine_temp=90.0) == "HIGH"

    def test_no_alert_when_below_all_thresholds(self):
        assert classify_severity(fault_count=3, max_engine_temp=95.0) is None

    def test_healthy_vehicle_generates_no_alert(self):
        assert classify_severity(fault_count=0, max_engine_temp=85.0) is None


class TestAlertPayloadStructure:
    """Validates the fields written to FAULT_NOTIFICATIONS."""

    REQUIRED_FIELDS = [
        "vin_reference", "fault_count", "max_engine_temp",
        "severity_label", "triggered_at", "alert_source", "acknowledged"
    ]

    def test_critical_alert_has_all_required_fields(self):
        payload = build_alert_payload("VIN_AWS_CRIT_001", 25, 132.0)
        assert payload is not None
        for field in self.REQUIRED_FIELDS:
            assert field in payload, f"Missing field: {field}"

    def test_alert_is_unacknowledged_by_default(self):
        payload = build_alert_payload("VIN_TEST", 15, 100.0)
        assert payload["acknowledged"] is False

    def test_alert_source_is_snowflake_task(self):
        payload = build_alert_payload("VIN_TEST", 15, 100.0)
        assert payload["alert_source"] == "SNOWFLAKE_TASK"

    def test_no_payload_returned_for_healthy_vehicle(self):
        payload = build_alert_payload("VIN_HEALTHY", 2, 88.0)
        assert payload is None

    def test_severity_label_is_valid_enum_value(self):
        valid_severities = {"LOW", "HIGH", "CRITICAL"}
        for faults, temp in [(25, 90), (15, 90), (2, 120)]:
            payload = build_alert_payload("VIN_X", faults, temp)
            if payload:
                assert payload["severity_label"] in valid_severities


class TestCriticalAlertsDataset:
    """
    Integration-style: Validates that our aws_critical_alerts.json test data
    (generated by generate_test_data.py) all produce HIGH or CRITICAL alerts.
    This proves the test dataset is fit for Story 1 end-to-end testing.
    """

    @pytest.fixture
    def critical_records(self):
        path = os.path.join(
            os.path.dirname(__file__), "..", "data",
            "raw_cloud_events", "aws_critical_alerts.json"
        )
        if not os.path.exists(path):
            pytest.skip("aws_critical_alerts.json not found — run generate_test_data.py first")
        with open(path) as f:
            return json.load(f)

    def test_all_critical_records_breach_a_threshold(self, critical_records):
        for record in critical_records:
            temp = record.get("engine_temp_c", 0)
            if not isinstance(temp, (int, float)):
                continue
            # Critical records are seeded with temp > 128 in generate_test_data.py
            assert temp > 115, f"VIN {record['vin']} temp {temp} should exceed HIGH threshold"

    def test_critical_records_generate_high_or_critical_alerts(self, critical_records):
        for record in critical_records:
            temp = record.get("engine_temp_c", 0)
            if not isinstance(temp, (int, float)):
                continue
            severity = classify_severity(fault_count=1, max_engine_temp=temp)
            assert severity in ("HIGH", "CRITICAL"), \
                f"VIN {record['vin']} with temp {temp} should alert but got: {severity}"

    def test_no_healthy_vehicles_in_critical_dataset(self, critical_records):
        """Guard against test data drift — critical file must not contain safe vehicles."""
        healthy_count = sum(
            1 for r in critical_records
            if isinstance(r.get("engine_temp_c"), (int, float))
            and classify_severity(1, r["engine_temp_c"]) is None
        )
        assert healthy_count == 0, f"{healthy_count} healthy VINs found in critical test dataset"
