name: 'automotive_copilot'
version: '1.0.0'
config-version: 2
profile: 'automotive_copilot'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  automotive_copilot:
    staging:
      +materialized: view
    marts:
      +materialized: table
